### ISSUE TITLE
modelo de datos de avances

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_crud#1]
se requiere realizar el modelo de datos para el sistema de tesorería en la sección de avances

**Comment by NRDaza** [comment]
# Modelo de datos avances

![Copy_of_New_Modelo_datos_Avance_Api_financiera-2021-01-28_09-09](https://user-images.githubusercontent.com/34488581/106151631-8d3d2180-614a-11eb-8d98-5d813e4d79cc.png)

### LINK 

Al modelo de datos se le realizan las siguientes modificaciones:
https://my.vertabelo.com/doc/2Ilp4DzJNIls0P5PImw8jQFgOiQn6BoJ

- Se cambia el tipo de datos de int a serial a todas las primary key.
- Todas las tablas ahora perteneces a un esquema llamado avances
- Respecto al modelo original se agregan las tablas referentes a especificaciones, información estudiante para practicas academicas
- Se eliminan tablas de etapa_requisito_avance, orden_pago, cuenta_especial, subtipo_avance_legalizacion,  concepto_legalizacion, etapa_avance_legalizacion, presupuesto_avance
- Se reubica tabla orden_pago_avance_legalizacion
-Se agrengan capos faltantes en algunas tablas como solicitud_avance, y los datos de la tabla avance_legalizacion_tipo se trasladan a una nueva tabla registro_avance_legalizacion

**Comment by BOTOOM** [comment]
- es necesario que unas 2 tablas ya que no tiene sentido que esten separadas, lo que debes hacer es meter dentro de la tabla `reintegro` los atributos d ela tabla `reintetro_avance_legalizacion` al hacer eso esa tabla desaparecerá y solo quedara `reintegro`
- la tabla `tipo_documento_afectante`  eliminala, en lo personal no e encuentro sentido a que este alli, pero si tienes una razon me la puedes comentar
- en `especificacion_avance` el nombre aparece como int, corrigelo porfa
- en `especificacion_avance` el atributo `valor` debe estar en la tabla `solicitud_esecificacion_tipo_avace`
- la tabla `solicitud_esecificacion_tipo_avace` cambiale el nombre a `especificacion_solicitud__tipo_avace`
- en `tipo_avance` el atributo `link_norma` dejalo de tipo `text` eso es un varchar que cambia de tamaño , para este caso es necesario
- en `aolicitud_avance` cambia el nombre de `cargo_id` por `cargo_ordenador_garto_id`, a `tipo_documento` te falto colocarle `_id`
- en `registro_avance_legalizacion` borra el campo `nombre tercero` eso se trae al consultar el tercero

**Comment by NRDaza** [comment]
Se realizan ajusten sugeridos, revisar en el  link publicado en el comentario anterior.

**Comment by NRDaza** [comment]
Se adiciona al modelo la tabla `norma `encargada de manejar los `Link de norma` de un `tipo de avance` dependiendo de la `vigencia`.
![Copy_of_New_Modelo_datos_Avance_Api_financiera-2021-02-05_11-40 (1)](https://user-images.githubusercontent.com/34488581/107062218-0ff75980-67a7-11eb-8321-10f1d9556328.png)
